### PR TITLE
19180 update dev doc

### PR DESCRIPTION
**Pull request by Jkeyuk**
- Adds version info to url if it was missing
- Update thumbnail download documentation

### CODE REVIEW

**Comment by Jkeyuk** [comment]
> I could be wrong, but thought it should be "A thumbnail is automatically generated when an image file is uploaded", instead of the image file's metadata.
> All other parts are good to go

Ya that should of read as:
>A thumbnails metadata is automatically generated when an image file's metadata is uploaded.

**Comment by cgendreau** [comment]
I think it should be "A thumbnail and its metadata are automatically generated when an image file's metadata is uploaded." no? We should not use the word meta entry since it`s an implementation detail.

**Comment by xuemeigan** [comment]
Agreed, no mention of meta entry is needed.  I guess we can call that "upload metadata" when store into minio. To me, upload usually refers to upload a file , not its metadata.

**Comment by Jkeyuk** [comment]
So for clarity I added both descriptions as they are both important.

> A thumbnail is automatically generated when an image file is uploaded.
> 
> A thumbnails metadata is automatically generated when an image file's metadata is uploaded. 

I believe the two descriptions are important for this section of the documentation. It is possible for a user of the api to think the thumbnails metadata is available right after the image upload, but that is not the case as the thumbnails meta is only available after the original image files meta is uploaded.

**Pull request merged**
